/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ActivityInstanceIncidentDto model module.
 * @module model/ActivityInstanceIncidentDto
 * @version 7.20.0
 */
export class ActivityInstanceIncidentDto {
  /**
   * Constructs a new <code>ActivityInstanceIncidentDto</code>.
   * An activity instance, incident pair.
   * @alias module:model/ActivityInstanceIncidentDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ActivityInstanceIncidentDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ActivityInstanceIncidentDto} obj Optional instance to populate.
   * @return {module:model/ActivityInstanceIncidentDto} The populated <code>ActivityInstanceIncidentDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ActivityInstanceIncidentDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('activityId'))
        obj.activityId = ApiClient.convertToType(data['activityId'], 'String');
    }
    return obj;
  }
}

/**
 * The id of the incident.
 * @member {String} id
 */
ActivityInstanceIncidentDto.prototype.id = undefined;

/**
 * The activity id in which the incident happened.
 * @member {String} activityId
 */
ActivityInstanceIncidentDto.prototype.activityId = undefined;

