/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AnnotationDto model module.
 * @module model/AnnotationDto
 * @version 7.20.0
 */
export class AnnotationDto {
  /**
   * Constructs a new <code>AnnotationDto</code>.
   * @alias module:model/AnnotationDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AnnotationDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnnotationDto} obj Optional instance to populate.
   * @return {module:model/AnnotationDto} The populated <code>AnnotationDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AnnotationDto();
      if (data.hasOwnProperty('annotation'))
        obj.annotation = ApiClient.convertToType(data['annotation'], 'String');
    }
    return obj;
  }
}

/**
 * The annotation value to put.
 * @member {String} annotation
 */
AnnotationDto.prototype.annotation = undefined;

