/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ExceptionDto} from './ExceptionDto';

/**
 * The AuthorizationExceptionDto model module.
 * @module model/AuthorizationExceptionDto
 * @version 7.20.0
 */
export class AuthorizationExceptionDto {
  /**
   * Constructs a new <code>AuthorizationExceptionDto</code>.
   * @alias module:model/AuthorizationExceptionDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AuthorizationExceptionDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthorizationExceptionDto} obj Optional instance to populate.
   * @return {module:model/AuthorizationExceptionDto} The populated <code>AuthorizationExceptionDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AuthorizationExceptionDto();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'Number');
    }
    return obj;
  }
}

/**
 * An exception class indicating the occurred error.
 * @member {String} type
 */
AuthorizationExceptionDto.prototype.type = undefined;

/**
 * A detailed message of the error.
 * @member {String} message
 */
AuthorizationExceptionDto.prototype.message = undefined;

/**
 * The code allows your client application to identify the error in an automated fashion. You can look up the meaning of all built-in codes and learn how to add custom codes in the [User Guide](https://docs.camunda.org/manual/develop/user-guide/process-engine/error-handling/#exception-codes).
 * @member {Number} code
 */
AuthorizationExceptionDto.prototype.code = undefined;

