/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PasswordPolicyRuleDto} from './PasswordPolicyRuleDto';

/**
 * The CheckPasswordPolicyRuleDto model module.
 * @module model/CheckPasswordPolicyRuleDto
 * @version 7.20.0
 */
export class CheckPasswordPolicyRuleDto {
  /**
   * Constructs a new <code>CheckPasswordPolicyRuleDto</code>.
   * @alias module:model/CheckPasswordPolicyRuleDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CheckPasswordPolicyRuleDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CheckPasswordPolicyRuleDto} obj Optional instance to populate.
   * @return {module:model/CheckPasswordPolicyRuleDto} The populated <code>CheckPasswordPolicyRuleDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CheckPasswordPolicyRuleDto();
      if (data.hasOwnProperty('placeholder'))
        obj.placeholder = ApiClient.convertToType(data['placeholder'], 'String');
      if (data.hasOwnProperty('parameter'))
        obj.parameter = ApiClient.convertToType(data['parameter'], {'String': 'String'});
    }
    return obj;
  }
}

/**
 * A placeholder string that contains the name of a password policy rule.
 * @member {String} placeholder
 */
CheckPasswordPolicyRuleDto.prototype.placeholder = undefined;

/**
 * A map that describes the characteristics of a password policy rule, such as the minimum number of digits.
 * @member {Object.<String, String>} parameter
 */
CheckPasswordPolicyRuleDto.prototype.parameter = undefined;

