/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CleanableHistoricProcessInstanceReportResultDto model module.
 * @module model/CleanableHistoricProcessInstanceReportResultDto
 * @version 7.20.0
 */
export class CleanableHistoricProcessInstanceReportResultDto {
  /**
   * Constructs a new <code>CleanableHistoricProcessInstanceReportResultDto</code>.
   * @alias module:model/CleanableHistoricProcessInstanceReportResultDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CleanableHistoricProcessInstanceReportResultDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CleanableHistoricProcessInstanceReportResultDto} obj Optional instance to populate.
   * @return {module:model/CleanableHistoricProcessInstanceReportResultDto} The populated <code>CleanableHistoricProcessInstanceReportResultDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CleanableHistoricProcessInstanceReportResultDto();
      if (data.hasOwnProperty('processDefinitionId'))
        obj.processDefinitionId = ApiClient.convertToType(data['processDefinitionId'], 'String');
      if (data.hasOwnProperty('processDefinitionKey'))
        obj.processDefinitionKey = ApiClient.convertToType(data['processDefinitionKey'], 'String');
      if (data.hasOwnProperty('processDefinitionName'))
        obj.processDefinitionName = ApiClient.convertToType(data['processDefinitionName'], 'String');
      if (data.hasOwnProperty('processDefinitionVersion'))
        obj.processDefinitionVersion = ApiClient.convertToType(data['processDefinitionVersion'], 'Number');
      if (data.hasOwnProperty('historyTimeToLive'))
        obj.historyTimeToLive = ApiClient.convertToType(data['historyTimeToLive'], 'Number');
      if (data.hasOwnProperty('finishedProcessInstanceCount'))
        obj.finishedProcessInstanceCount = ApiClient.convertToType(data['finishedProcessInstanceCount'], 'Number');
      if (data.hasOwnProperty('cleanableProcessInstanceCount'))
        obj.cleanableProcessInstanceCount = ApiClient.convertToType(data['cleanableProcessInstanceCount'], 'Number');
      if (data.hasOwnProperty('tenantId'))
        obj.tenantId = ApiClient.convertToType(data['tenantId'], 'String');
    }
    return obj;
  }
}

/**
 * The id of the process definition.
 * @member {String} processDefinitionId
 */
CleanableHistoricProcessInstanceReportResultDto.prototype.processDefinitionId = undefined;

/**
 * The key of the process definition.
 * @member {String} processDefinitionKey
 */
CleanableHistoricProcessInstanceReportResultDto.prototype.processDefinitionKey = undefined;

/**
 * The name of the process definition.
 * @member {String} processDefinitionName
 */
CleanableHistoricProcessInstanceReportResultDto.prototype.processDefinitionName = undefined;

/**
 * The version of the process definition.
 * @member {Number} processDefinitionVersion
 */
CleanableHistoricProcessInstanceReportResultDto.prototype.processDefinitionVersion = undefined;

/**
 * The history time to live of the process definition.
 * @member {Number} historyTimeToLive
 */
CleanableHistoricProcessInstanceReportResultDto.prototype.historyTimeToLive = undefined;

/**
 * The count of the finished historic process instances.
 * @member {Number} finishedProcessInstanceCount
 */
CleanableHistoricProcessInstanceReportResultDto.prototype.finishedProcessInstanceCount = undefined;

/**
 * The count of the cleanable historic process instances, referring to history time to live.
 * @member {Number} cleanableProcessInstanceCount
 */
CleanableHistoricProcessInstanceReportResultDto.prototype.cleanableProcessInstanceCount = undefined;

/**
 * The tenant id of the process definition.
 * @member {String} tenantId
 */
CleanableHistoricProcessInstanceReportResultDto.prototype.tenantId = undefined;

