/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CleanableHistoricBatchReportResultDto model module.
 * @module model/CleanableHistoricBatchReportResultDto
 * @version 7.20.0
 */
export class CleanableHistoricBatchReportResultDto {
  /**
   * Constructs a new <code>CleanableHistoricBatchReportResultDto</code>.
   * @alias module:model/CleanableHistoricBatchReportResultDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CleanableHistoricBatchReportResultDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CleanableHistoricBatchReportResultDto} obj Optional instance to populate.
   * @return {module:model/CleanableHistoricBatchReportResultDto} The populated <code>CleanableHistoricBatchReportResultDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CleanableHistoricBatchReportResultDto();
      if (data.hasOwnProperty('batchType'))
        obj.batchType = ApiClient.convertToType(data['batchType'], 'String');
      if (data.hasOwnProperty('historyTimeToLive'))
        obj.historyTimeToLive = ApiClient.convertToType(data['historyTimeToLive'], 'Number');
      if (data.hasOwnProperty('finishedBatchesCount'))
        obj.finishedBatchesCount = ApiClient.convertToType(data['finishedBatchesCount'], 'Number');
      if (data.hasOwnProperty('cleanableBatchesCount'))
        obj.cleanableBatchesCount = ApiClient.convertToType(data['cleanableBatchesCount'], 'Number');
    }
    return obj;
  }
}

/**
 * The type of the batch operation.
 * @member {String} batchType
 */
CleanableHistoricBatchReportResultDto.prototype.batchType = undefined;

/**
 * The history time to live of the batch operation.
 * @member {Number} historyTimeToLive
 */
CleanableHistoricBatchReportResultDto.prototype.historyTimeToLive = undefined;

/**
 * The count of the finished batch operations.
 * @member {Number} finishedBatchesCount
 */
CleanableHistoricBatchReportResultDto.prototype.finishedBatchesCount = undefined;

/**
 * The count of the cleanable historic batch operations, referring to history time to live.
 * @member {Number} cleanableBatchesCount
 */
CleanableHistoricBatchReportResultDto.prototype.cleanableBatchesCount = undefined;

