/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The EventSubscriptionQueryDtoSorting model module.
 * @module model/EventSubscriptionQueryDtoSorting
 * @version 7.20.0
 */
export class EventSubscriptionQueryDtoSorting {
  /**
   * Constructs a new <code>EventSubscriptionQueryDtoSorting</code>.
   * @alias module:model/EventSubscriptionQueryDtoSorting
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EventSubscriptionQueryDtoSorting</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventSubscriptionQueryDtoSorting} obj Optional instance to populate.
   * @return {module:model/EventSubscriptionQueryDtoSorting} The populated <code>EventSubscriptionQueryDtoSorting</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EventSubscriptionQueryDtoSorting();
      if (data.hasOwnProperty('sortBy'))
        obj.sortBy = ApiClient.convertToType(data['sortBy'], 'String');
      if (data.hasOwnProperty('sortOrder'))
        obj.sortOrder = ApiClient.convertToType(data['sortOrder'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>sortBy</code> property.
 * @enum {String}
 * @readonly
 */
EventSubscriptionQueryDtoSorting.SortByEnum = {
  /**
   * value: "created"
   * @const
   */
  created: "created",

  /**
   * value: "tenantId"
   * @const
   */
  tenantId: "tenantId"
};
/**
 * Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter.
 * @member {module:model/EventSubscriptionQueryDtoSorting.SortByEnum} sortBy
 */
EventSubscriptionQueryDtoSorting.prototype.sortBy = undefined;

/**
 * Allowed values for the <code>sortOrder</code> property.
 * @enum {String}
 * @readonly
 */
EventSubscriptionQueryDtoSorting.SortOrderEnum = {
  /**
   * value: "asc"
   * @const
   */
  asc: "asc",

  /**
   * value: "desc"
   * @const
   */
  desc: "desc"
};
/**
 * Sort the results in a given order. Values may be `asc` for ascending order or `desc` for descending order. Must be used in conjunction with the sortBy parameter.
 * @member {module:model/EventSubscriptionQueryDtoSorting.SortOrderEnum} sortOrder
 */
EventSubscriptionQueryDtoSorting.prototype.sortOrder = undefined;

