/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {VariableValueDto} from './VariableValueDto';

/**
 * The ExecutionTriggerDto model module.
 * @module model/ExecutionTriggerDto
 * @version 7.20.0
 */
export class ExecutionTriggerDto {
  /**
   * Constructs a new <code>ExecutionTriggerDto</code>.
   * @alias module:model/ExecutionTriggerDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ExecutionTriggerDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExecutionTriggerDto} obj Optional instance to populate.
   * @return {module:model/ExecutionTriggerDto} The populated <code>ExecutionTriggerDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExecutionTriggerDto();
      if (data.hasOwnProperty('variables'))
        obj.variables = ApiClient.convertToType(data['variables'], {'String': VariableValueDto});
    }
    return obj;
  }
}

/**
 * A JSON object containing variable key-value pairs. Each key is a variable name and each value a JSON variable value object.
 * @member {Object.<String, module:model/VariableValueDto>} variables
 */
ExecutionTriggerDto.prototype.variables = undefined;

