/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GroupQueryDtoSorting model module.
 * @module model/GroupQueryDtoSorting
 * @version 7.20.0
 */
export class GroupQueryDtoSorting {
  /**
   * Constructs a new <code>GroupQueryDtoSorting</code>.
   * @alias module:model/GroupQueryDtoSorting
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GroupQueryDtoSorting</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupQueryDtoSorting} obj Optional instance to populate.
   * @return {module:model/GroupQueryDtoSorting} The populated <code>GroupQueryDtoSorting</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GroupQueryDtoSorting();
      if (data.hasOwnProperty('sortBy'))
        obj.sortBy = ApiClient.convertToType(data['sortBy'], 'String');
      if (data.hasOwnProperty('sortOrder'))
        obj.sortOrder = ApiClient.convertToType(data['sortOrder'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>sortBy</code> property.
 * @enum {String}
 * @readonly
 */
GroupQueryDtoSorting.SortByEnum = {
  /**
   * value: "id"
   * @const
   */
  id: "id",

  /**
   * value: "name"
   * @const
   */
  name: "name",

  /**
   * value: "type"
   * @const
   */
  type: "type"
};
/**
 * Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter.
 * @member {module:model/GroupQueryDtoSorting.SortByEnum} sortBy
 */
GroupQueryDtoSorting.prototype.sortBy = undefined;

/**
 * Allowed values for the <code>sortOrder</code> property.
 * @enum {String}
 * @readonly
 */
GroupQueryDtoSorting.SortOrderEnum = {
  /**
   * value: "asc"
   * @const
   */
  asc: "asc",

  /**
   * value: "desc"
   * @const
   */
  desc: "desc"
};
/**
 * Sort the results in a given order. Values may be `asc` for ascending order or `desc` for descending order. Must be used in conjunction with the sortBy parameter.
 * @member {module:model/GroupQueryDtoSorting.SortOrderEnum} sortOrder
 */
GroupQueryDtoSorting.prototype.sortOrder = undefined;

