/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The HandleExternalTaskDto model module.
 * @module model/HandleExternalTaskDto
 * @version 7.20.0
 */
export class HandleExternalTaskDto {
  /**
   * Constructs a new <code>HandleExternalTaskDto</code>.
   * @alias module:model/HandleExternalTaskDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HandleExternalTaskDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HandleExternalTaskDto} obj Optional instance to populate.
   * @return {module:model/HandleExternalTaskDto} The populated <code>HandleExternalTaskDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HandleExternalTaskDto();
      if (data.hasOwnProperty('workerId'))
        obj.workerId = ApiClient.convertToType(data['workerId'], 'String');
    }
    return obj;
  }
}

/**
 * **Mandatory.** The ID of the worker who is performing the operation on the external task. If the task is already locked, must match the id of the worker who has most recently locked the task.
 * @member {String} workerId
 */
HandleExternalTaskDto.prototype.workerId = undefined;

