/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {HistoricExternalTaskLogQueryDtoSorting} from './HistoricExternalTaskLogQueryDtoSorting';

/**
 * The HistoricExternalTaskLogQueryDto model module.
 * @module model/HistoricExternalTaskLogQueryDto
 * @version 7.20.0
 */
export class HistoricExternalTaskLogQueryDto {
  /**
   * Constructs a new <code>HistoricExternalTaskLogQueryDto</code>.
   * A Historic External Task Log instance query which defines a list of Historic External Task Log instances
   * @alias module:model/HistoricExternalTaskLogQueryDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HistoricExternalTaskLogQueryDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HistoricExternalTaskLogQueryDto} obj Optional instance to populate.
   * @return {module:model/HistoricExternalTaskLogQueryDto} The populated <code>HistoricExternalTaskLogQueryDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HistoricExternalTaskLogQueryDto();
      if (data.hasOwnProperty('logId'))
        obj.logId = ApiClient.convertToType(data['logId'], 'String');
      if (data.hasOwnProperty('externalTaskId'))
        obj.externalTaskId = ApiClient.convertToType(data['externalTaskId'], 'String');
      if (data.hasOwnProperty('topicName'))
        obj.topicName = ApiClient.convertToType(data['topicName'], 'String');
      if (data.hasOwnProperty('workerId'))
        obj.workerId = ApiClient.convertToType(data['workerId'], 'String');
      if (data.hasOwnProperty('errorMessage'))
        obj.errorMessage = ApiClient.convertToType(data['errorMessage'], 'String');
      if (data.hasOwnProperty('activityIdIn'))
        obj.activityIdIn = ApiClient.convertToType(data['activityIdIn'], ['String']);
      if (data.hasOwnProperty('activityInstanceIdIn'))
        obj.activityInstanceIdIn = ApiClient.convertToType(data['activityInstanceIdIn'], ['String']);
      if (data.hasOwnProperty('executionIdIn'))
        obj.executionIdIn = ApiClient.convertToType(data['executionIdIn'], ['String']);
      if (data.hasOwnProperty('processInstanceId'))
        obj.processInstanceId = ApiClient.convertToType(data['processInstanceId'], 'String');
      if (data.hasOwnProperty('processDefinitionId'))
        obj.processDefinitionId = ApiClient.convertToType(data['processDefinitionId'], 'String');
      if (data.hasOwnProperty('processDefinitionKey'))
        obj.processDefinitionKey = ApiClient.convertToType(data['processDefinitionKey'], 'String');
      if (data.hasOwnProperty('tenantIdIn'))
        obj.tenantIdIn = ApiClient.convertToType(data['tenantIdIn'], ['String']);
      if (data.hasOwnProperty('withoutTenantId'))
        obj.withoutTenantId = ApiClient.convertToType(data['withoutTenantId'], 'Boolean');
      if (data.hasOwnProperty('priorityLowerThanOrEquals'))
        obj.priorityLowerThanOrEquals = ApiClient.convertToType(data['priorityLowerThanOrEquals'], 'Number');
      if (data.hasOwnProperty('priorityHigherThanOrEquals'))
        obj.priorityHigherThanOrEquals = ApiClient.convertToType(data['priorityHigherThanOrEquals'], 'Number');
      if (data.hasOwnProperty('creationLog'))
        obj.creationLog = ApiClient.convertToType(data['creationLog'], 'Boolean');
      if (data.hasOwnProperty('failureLog'))
        obj.failureLog = ApiClient.convertToType(data['failureLog'], 'Boolean');
      if (data.hasOwnProperty('successLog'))
        obj.successLog = ApiClient.convertToType(data['successLog'], 'Boolean');
      if (data.hasOwnProperty('deletionLog'))
        obj.deletionLog = ApiClient.convertToType(data['deletionLog'], 'Boolean');
      if (data.hasOwnProperty('sorting'))
        obj.sorting = ApiClient.convertToType(data['sorting'], [HistoricExternalTaskLogQueryDtoSorting]);
    }
    return obj;
  }
}

/**
 * Filter by historic external task log id.
 * @member {String} logId
 */
HistoricExternalTaskLogQueryDto.prototype.logId = undefined;

/**
 * Filter by external task id.
 * @member {String} externalTaskId
 */
HistoricExternalTaskLogQueryDto.prototype.externalTaskId = undefined;

/**
 * Filter by an external task topic.
 * @member {String} topicName
 */
HistoricExternalTaskLogQueryDto.prototype.topicName = undefined;

/**
 * Filter by the id of the worker that the task was most recently locked by.
 * @member {String} workerId
 */
HistoricExternalTaskLogQueryDto.prototype.workerId = undefined;

/**
 * Filter by external task exception message.
 * @member {String} errorMessage
 */
HistoricExternalTaskLogQueryDto.prototype.errorMessage = undefined;

/**
 * Only include historic external task logs which belong to one of the passed activity ids.
 * @member {Array.<String>} activityIdIn
 */
HistoricExternalTaskLogQueryDto.prototype.activityIdIn = undefined;

/**
 * Only include historic external task logs which belong to one of the passed activity instance ids.
 * @member {Array.<String>} activityInstanceIdIn
 */
HistoricExternalTaskLogQueryDto.prototype.activityInstanceIdIn = undefined;

/**
 * Only include historic external task logs which belong to one of the passed execution ids.
 * @member {Array.<String>} executionIdIn
 */
HistoricExternalTaskLogQueryDto.prototype.executionIdIn = undefined;

/**
 * Filter by process instance id.
 * @member {String} processInstanceId
 */
HistoricExternalTaskLogQueryDto.prototype.processInstanceId = undefined;

/**
 * Filter by process definition id.
 * @member {String} processDefinitionId
 */
HistoricExternalTaskLogQueryDto.prototype.processDefinitionId = undefined;

/**
 * Filter by process definition key.
 * @member {String} processDefinitionKey
 */
HistoricExternalTaskLogQueryDto.prototype.processDefinitionKey = undefined;

/**
 * Only include historic external task log entries which belong to one of the passed and comma-separated tenant ids.
 * @member {Array.<String>} tenantIdIn
 */
HistoricExternalTaskLogQueryDto.prototype.tenantIdIn = undefined;

/**
 * Only include historic external task log entries that belong to no tenant. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} withoutTenantId
 */
HistoricExternalTaskLogQueryDto.prototype.withoutTenantId = undefined;

/**
 * Only include logs for which the associated external task had a priority lower than or equal to the given value. Value must be a valid `long` value.
 * @member {Number} priorityLowerThanOrEquals
 */
HistoricExternalTaskLogQueryDto.prototype.priorityLowerThanOrEquals = undefined;

/**
 * Only include logs for which the associated external task had a priority higher than or equal to the given value. Value must be a valid `long` value.
 * @member {Number} priorityHigherThanOrEquals
 */
HistoricExternalTaskLogQueryDto.prototype.priorityHigherThanOrEquals = undefined;

/**
 * Only include creation logs. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} creationLog
 */
HistoricExternalTaskLogQueryDto.prototype.creationLog = undefined;

/**
 * Only include failure logs. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} failureLog
 */
HistoricExternalTaskLogQueryDto.prototype.failureLog = undefined;

/**
 * Only include success logs. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} successLog
 */
HistoricExternalTaskLogQueryDto.prototype.successLog = undefined;

/**
 * Only include deletion logs. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} deletionLog
 */
HistoricExternalTaskLogQueryDto.prototype.deletionLog = undefined;

/**
 * An array of criteria to sort the result by. Each element of the array is                        an object that specifies one ordering. The position in the array                        identifies the rank of an ordering, i.e., whether it is primary, secondary,                        etc. Sorting has no effect for `count` endpoints.
 * @member {Array.<module:model/HistoricExternalTaskLogQueryDtoSorting>} sorting
 */
HistoricExternalTaskLogQueryDto.prototype.sorting = undefined;

