/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The HistoryTimeToLiveDto model module.
 * @module model/HistoryTimeToLiveDto
 * @version 7.20.0
 */
export class HistoryTimeToLiveDto {
  /**
   * Constructs a new <code>HistoryTimeToLiveDto</code>.
   * @alias module:model/HistoryTimeToLiveDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HistoryTimeToLiveDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HistoryTimeToLiveDto} obj Optional instance to populate.
   * @return {module:model/HistoryTimeToLiveDto} The populated <code>HistoryTimeToLiveDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HistoryTimeToLiveDto();
      if (data.hasOwnProperty('historyTimeToLive'))
        obj.historyTimeToLive = ApiClient.convertToType(data['historyTimeToLive'], 'Number');
    }
    return obj;
  }
}

/**
 * New value for historyTimeToLive field of the definition. Can be `null`. Can not be negative.
 * @member {Number} historyTimeToLive
 */
HistoryTimeToLiveDto.prototype.historyTimeToLive = undefined;

