/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The HistoricDetailQueryDtoSorting model module.
 * @module model/HistoricDetailQueryDtoSorting
 * @version 7.20.0
 */
export class HistoricDetailQueryDtoSorting {
  /**
   * Constructs a new <code>HistoricDetailQueryDtoSorting</code>.
   * @alias module:model/HistoricDetailQueryDtoSorting
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HistoricDetailQueryDtoSorting</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HistoricDetailQueryDtoSorting} obj Optional instance to populate.
   * @return {module:model/HistoricDetailQueryDtoSorting} The populated <code>HistoricDetailQueryDtoSorting</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HistoricDetailQueryDtoSorting();
      if (data.hasOwnProperty('sortBy'))
        obj.sortBy = ApiClient.convertToType(data['sortBy'], 'String');
      if (data.hasOwnProperty('sortOrder'))
        obj.sortOrder = ApiClient.convertToType(data['sortOrder'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>sortBy</code> property.
 * @enum {String}
 * @readonly
 */
HistoricDetailQueryDtoSorting.SortByEnum = {
  /**
   * value: "processInstanceId"
   * @const
   */
  processInstanceId: "processInstanceId",

  /**
   * value: "variableName"
   * @const
   */
  variableName: "variableName",

  /**
   * value: "variableType"
   * @const
   */
  variableType: "variableType",

  /**
   * value: "variableRevision"
   * @const
   */
  variableRevision: "variableRevision",

  /**
   * value: "formPropertyId"
   * @const
   */
  formPropertyId: "formPropertyId",

  /**
   * value: "time"
   * @const
   */
  time: "time",

  /**
   * value: "occurrence"
   * @const
   */
  occurrence: "occurrence",

  /**
   * value: "tenantId"
   * @const
   */
  tenantId: "tenantId"
};
/**
 * Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter.
 * @member {module:model/HistoricDetailQueryDtoSorting.SortByEnum} sortBy
 */
HistoricDetailQueryDtoSorting.prototype.sortBy = undefined;

/**
 * Allowed values for the <code>sortOrder</code> property.
 * @enum {String}
 * @readonly
 */
HistoricDetailQueryDtoSorting.SortOrderEnum = {
  /**
   * value: "asc"
   * @const
   */
  asc: "asc",

  /**
   * value: "desc"
   * @const
   */
  desc: "desc"
};
/**
 * Sort the results in a given order. Values may be `asc` for ascending order or `desc` for descending order. Must be used in conjunction with the sortBy parameter.
 * @member {module:model/HistoricDetailQueryDtoSorting.SortOrderEnum} sortOrder
 */
HistoricDetailQueryDtoSorting.prototype.sortOrder = undefined;

