/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {HistoricTaskInstanceQueryDtoSorting} from './HistoricTaskInstanceQueryDtoSorting';
import {VariableQueryParameterDto} from './VariableQueryParameterDto';

/**
 * The HistoricTaskInstanceQueryDto model module.
 * @module model/HistoricTaskInstanceQueryDto
 * @version 7.20.0
 */
export class HistoricTaskInstanceQueryDto {
  /**
   * Constructs a new <code>HistoricTaskInstanceQueryDto</code>.
   * A Historic Task instance query which defines a list of Historic Task instances
   * @alias module:model/HistoricTaskInstanceQueryDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HistoricTaskInstanceQueryDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HistoricTaskInstanceQueryDto} obj Optional instance to populate.
   * @return {module:model/HistoricTaskInstanceQueryDto} The populated <code>HistoricTaskInstanceQueryDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HistoricTaskInstanceQueryDto();
      if (data.hasOwnProperty('taskId'))
        obj.taskId = ApiClient.convertToType(data['taskId'], 'String');
      if (data.hasOwnProperty('taskParentTaskId'))
        obj.taskParentTaskId = ApiClient.convertToType(data['taskParentTaskId'], 'String');
      if (data.hasOwnProperty('processInstanceId'))
        obj.processInstanceId = ApiClient.convertToType(data['processInstanceId'], 'String');
      if (data.hasOwnProperty('processInstanceBusinessKey'))
        obj.processInstanceBusinessKey = ApiClient.convertToType(data['processInstanceBusinessKey'], 'String');
      if (data.hasOwnProperty('processInstanceBusinessKeyIn'))
        obj.processInstanceBusinessKeyIn = ApiClient.convertToType(data['processInstanceBusinessKeyIn'], ['String']);
      if (data.hasOwnProperty('processInstanceBusinessKeyLike'))
        obj.processInstanceBusinessKeyLike = ApiClient.convertToType(data['processInstanceBusinessKeyLike'], 'String');
      if (data.hasOwnProperty('executionId'))
        obj.executionId = ApiClient.convertToType(data['executionId'], 'String');
      if (data.hasOwnProperty('processDefinitionId'))
        obj.processDefinitionId = ApiClient.convertToType(data['processDefinitionId'], 'String');
      if (data.hasOwnProperty('processDefinitionKey'))
        obj.processDefinitionKey = ApiClient.convertToType(data['processDefinitionKey'], 'String');
      if (data.hasOwnProperty('processDefinitionName'))
        obj.processDefinitionName = ApiClient.convertToType(data['processDefinitionName'], 'String');
      if (data.hasOwnProperty('caseInstanceId'))
        obj.caseInstanceId = ApiClient.convertToType(data['caseInstanceId'], 'String');
      if (data.hasOwnProperty('caseExecutionId'))
        obj.caseExecutionId = ApiClient.convertToType(data['caseExecutionId'], 'String');
      if (data.hasOwnProperty('caseDefinitionId'))
        obj.caseDefinitionId = ApiClient.convertToType(data['caseDefinitionId'], 'String');
      if (data.hasOwnProperty('caseDefinitionKey'))
        obj.caseDefinitionKey = ApiClient.convertToType(data['caseDefinitionKey'], 'String');
      if (data.hasOwnProperty('caseDefinitionName'))
        obj.caseDefinitionName = ApiClient.convertToType(data['caseDefinitionName'], 'String');
      if (data.hasOwnProperty('activityInstanceIdIn'))
        obj.activityInstanceIdIn = ApiClient.convertToType(data['activityInstanceIdIn'], ['String']);
      if (data.hasOwnProperty('taskName'))
        obj.taskName = ApiClient.convertToType(data['taskName'], 'String');
      if (data.hasOwnProperty('taskNameLike'))
        obj.taskNameLike = ApiClient.convertToType(data['taskNameLike'], 'String');
      if (data.hasOwnProperty('taskDescription'))
        obj.taskDescription = ApiClient.convertToType(data['taskDescription'], 'String');
      if (data.hasOwnProperty('taskDescriptionLike'))
        obj.taskDescriptionLike = ApiClient.convertToType(data['taskDescriptionLike'], 'String');
      if (data.hasOwnProperty('taskDefinitionKey'))
        obj.taskDefinitionKey = ApiClient.convertToType(data['taskDefinitionKey'], 'String');
      if (data.hasOwnProperty('taskDefinitionKeyIn'))
        obj.taskDefinitionKeyIn = ApiClient.convertToType(data['taskDefinitionKeyIn'], ['String']);
      if (data.hasOwnProperty('taskDeleteReason'))
        obj.taskDeleteReason = ApiClient.convertToType(data['taskDeleteReason'], 'String');
      if (data.hasOwnProperty('taskDeleteReasonLike'))
        obj.taskDeleteReasonLike = ApiClient.convertToType(data['taskDeleteReasonLike'], 'String');
      if (data.hasOwnProperty('taskAssignee'))
        obj.taskAssignee = ApiClient.convertToType(data['taskAssignee'], 'String');
      if (data.hasOwnProperty('taskAssigneeLike'))
        obj.taskAssigneeLike = ApiClient.convertToType(data['taskAssigneeLike'], 'String');
      if (data.hasOwnProperty('taskOwner'))
        obj.taskOwner = ApiClient.convertToType(data['taskOwner'], 'String');
      if (data.hasOwnProperty('taskOwnerLike'))
        obj.taskOwnerLike = ApiClient.convertToType(data['taskOwnerLike'], 'String');
      if (data.hasOwnProperty('taskPriority'))
        obj.taskPriority = ApiClient.convertToType(data['taskPriority'], 'Number');
      if (data.hasOwnProperty('assigned'))
        obj.assigned = ApiClient.convertToType(data['assigned'], 'Boolean');
      if (data.hasOwnProperty('unassigned'))
        obj.unassigned = ApiClient.convertToType(data['unassigned'], 'Boolean');
      if (data.hasOwnProperty('finished'))
        obj.finished = ApiClient.convertToType(data['finished'], 'Boolean');
      if (data.hasOwnProperty('unfinished'))
        obj.unfinished = ApiClient.convertToType(data['unfinished'], 'Boolean');
      if (data.hasOwnProperty('processFinished'))
        obj.processFinished = ApiClient.convertToType(data['processFinished'], 'Boolean');
      if (data.hasOwnProperty('processUnfinished'))
        obj.processUnfinished = ApiClient.convertToType(data['processUnfinished'], 'Boolean');
      if (data.hasOwnProperty('taskDueDate'))
        obj.taskDueDate = ApiClient.convertToType(data['taskDueDate'], 'Date');
      if (data.hasOwnProperty('taskDueDateBefore'))
        obj.taskDueDateBefore = ApiClient.convertToType(data['taskDueDateBefore'], 'Date');
      if (data.hasOwnProperty('taskDueDateAfter'))
        obj.taskDueDateAfter = ApiClient.convertToType(data['taskDueDateAfter'], 'Date');
      if (data.hasOwnProperty('withoutTaskDueDate'))
        obj.withoutTaskDueDate = ApiClient.convertToType(data['withoutTaskDueDate'], 'Boolean');
      if (data.hasOwnProperty('taskFollowUpDate'))
        obj.taskFollowUpDate = ApiClient.convertToType(data['taskFollowUpDate'], 'Date');
      if (data.hasOwnProperty('taskFollowUpDateBefore'))
        obj.taskFollowUpDateBefore = ApiClient.convertToType(data['taskFollowUpDateBefore'], 'Date');
      if (data.hasOwnProperty('taskFollowUpDateAfter'))
        obj.taskFollowUpDateAfter = ApiClient.convertToType(data['taskFollowUpDateAfter'], 'Date');
      if (data.hasOwnProperty('startedBefore'))
        obj.startedBefore = ApiClient.convertToType(data['startedBefore'], 'Date');
      if (data.hasOwnProperty('startedAfter'))
        obj.startedAfter = ApiClient.convertToType(data['startedAfter'], 'Date');
      if (data.hasOwnProperty('finishedBefore'))
        obj.finishedBefore = ApiClient.convertToType(data['finishedBefore'], 'Date');
      if (data.hasOwnProperty('finishedAfter'))
        obj.finishedAfter = ApiClient.convertToType(data['finishedAfter'], 'Date');
      if (data.hasOwnProperty('tenantIdIn'))
        obj.tenantIdIn = ApiClient.convertToType(data['tenantIdIn'], ['String']);
      if (data.hasOwnProperty('withoutTenantId'))
        obj.withoutTenantId = ApiClient.convertToType(data['withoutTenantId'], 'Boolean');
      if (data.hasOwnProperty('taskVariables'))
        obj.taskVariables = ApiClient.convertToType(data['taskVariables'], [VariableQueryParameterDto]);
      if (data.hasOwnProperty('processVariables'))
        obj.processVariables = ApiClient.convertToType(data['processVariables'], [VariableQueryParameterDto]);
      if (data.hasOwnProperty('variableNamesIgnoreCase'))
        obj.variableNamesIgnoreCase = ApiClient.convertToType(data['variableNamesIgnoreCase'], 'Boolean');
      if (data.hasOwnProperty('variableValuesIgnoreCase'))
        obj.variableValuesIgnoreCase = ApiClient.convertToType(data['variableValuesIgnoreCase'], 'Boolean');
      if (data.hasOwnProperty('taskInvolvedUser'))
        obj.taskInvolvedUser = ApiClient.convertToType(data['taskInvolvedUser'], 'String');
      if (data.hasOwnProperty('taskInvolvedGroup'))
        obj.taskInvolvedGroup = ApiClient.convertToType(data['taskInvolvedGroup'], 'String');
      if (data.hasOwnProperty('taskHadCandidateUser'))
        obj.taskHadCandidateUser = ApiClient.convertToType(data['taskHadCandidateUser'], 'String');
      if (data.hasOwnProperty('taskHadCandidateGroup'))
        obj.taskHadCandidateGroup = ApiClient.convertToType(data['taskHadCandidateGroup'], 'String');
      if (data.hasOwnProperty('withCandidateGroups'))
        obj.withCandidateGroups = ApiClient.convertToType(data['withCandidateGroups'], 'Boolean');
      if (data.hasOwnProperty('withoutCandidateGroups'))
        obj.withoutCandidateGroups = ApiClient.convertToType(data['withoutCandidateGroups'], 'Boolean');
      if (data.hasOwnProperty('orQueries'))
        obj.orQueries = ApiClient.convertToType(data['orQueries'], [HistoricTaskInstanceQueryDto]);
      if (data.hasOwnProperty('sorting'))
        obj.sorting = ApiClient.convertToType(data['sorting'], [HistoricTaskInstanceQueryDtoSorting]);
    }
    return obj;
  }
}

/**
 * Filter by task id.
 * @member {String} taskId
 */
HistoricTaskInstanceQueryDto.prototype.taskId = undefined;

/**
 * Filter by parent task id.
 * @member {String} taskParentTaskId
 */
HistoricTaskInstanceQueryDto.prototype.taskParentTaskId = undefined;

/**
 * Filter by process instance id.
 * @member {String} processInstanceId
 */
HistoricTaskInstanceQueryDto.prototype.processInstanceId = undefined;

/**
 * Filter by process instance business key.
 * @member {String} processInstanceBusinessKey
 */
HistoricTaskInstanceQueryDto.prototype.processInstanceBusinessKey = undefined;

/**
 * Filter by process instances with one of the give business keys. The keys need to be in a comma-separated list.
 * @member {Array.<String>} processInstanceBusinessKeyIn
 */
HistoricTaskInstanceQueryDto.prototype.processInstanceBusinessKeyIn = undefined;

/**
 * Filter by  process instance business key that has the parameter value as a substring.
 * @member {String} processInstanceBusinessKeyLike
 */
HistoricTaskInstanceQueryDto.prototype.processInstanceBusinessKeyLike = undefined;

/**
 * Filter by the id of the execution that executed the task.
 * @member {String} executionId
 */
HistoricTaskInstanceQueryDto.prototype.executionId = undefined;

/**
 * Filter by process definition id.
 * @member {String} processDefinitionId
 */
HistoricTaskInstanceQueryDto.prototype.processDefinitionId = undefined;

/**
 * Restrict to tasks that belong to a process definition with the given key.
 * @member {String} processDefinitionKey
 */
HistoricTaskInstanceQueryDto.prototype.processDefinitionKey = undefined;

/**
 * Restrict to tasks that belong to a process definition with the given name.
 * @member {String} processDefinitionName
 */
HistoricTaskInstanceQueryDto.prototype.processDefinitionName = undefined;

/**
 * Filter by case instance id.
 * @member {String} caseInstanceId
 */
HistoricTaskInstanceQueryDto.prototype.caseInstanceId = undefined;

/**
 * Filter by the id of the case execution that executed the task.
 * @member {String} caseExecutionId
 */
HistoricTaskInstanceQueryDto.prototype.caseExecutionId = undefined;

/**
 * Filter by case definition id.
 * @member {String} caseDefinitionId
 */
HistoricTaskInstanceQueryDto.prototype.caseDefinitionId = undefined;

/**
 * Restrict to tasks that belong to a case definition with the given key.
 * @member {String} caseDefinitionKey
 */
HistoricTaskInstanceQueryDto.prototype.caseDefinitionKey = undefined;

/**
 * Restrict to tasks that belong to a case definition with the given name.
 * @member {String} caseDefinitionName
 */
HistoricTaskInstanceQueryDto.prototype.caseDefinitionName = undefined;

/**
 * Only include tasks which belong to one of the passed  activity instance ids.
 * @member {Array.<String>} activityInstanceIdIn
 */
HistoricTaskInstanceQueryDto.prototype.activityInstanceIdIn = undefined;

/**
 * Restrict to tasks that have the given name.
 * @member {String} taskName
 */
HistoricTaskInstanceQueryDto.prototype.taskName = undefined;

/**
 * Restrict to tasks that have a name with the given parameter value as substring.
 * @member {String} taskNameLike
 */
HistoricTaskInstanceQueryDto.prototype.taskNameLike = undefined;

/**
 * Restrict to tasks that have the given description.
 * @member {String} taskDescription
 */
HistoricTaskInstanceQueryDto.prototype.taskDescription = undefined;

/**
 * Restrict to tasks that have a description that has the parameter value as a substring.
 * @member {String} taskDescriptionLike
 */
HistoricTaskInstanceQueryDto.prototype.taskDescriptionLike = undefined;

/**
 * Restrict to tasks that have the given key.
 * @member {String} taskDefinitionKey
 */
HistoricTaskInstanceQueryDto.prototype.taskDefinitionKey = undefined;

/**
 * Restrict to tasks that have one of the passed  task definition keys.
 * @member {Array.<String>} taskDefinitionKeyIn
 */
HistoricTaskInstanceQueryDto.prototype.taskDefinitionKeyIn = undefined;

/**
 * Restrict to tasks that have the given delete reason.
 * @member {String} taskDeleteReason
 */
HistoricTaskInstanceQueryDto.prototype.taskDeleteReason = undefined;

/**
 * Restrict to tasks that have a delete reason that has the parameter value as a substring.
 * @member {String} taskDeleteReasonLike
 */
HistoricTaskInstanceQueryDto.prototype.taskDeleteReasonLike = undefined;

/**
 * Restrict to tasks that the given user is assigned to.
 * @member {String} taskAssignee
 */
HistoricTaskInstanceQueryDto.prototype.taskAssignee = undefined;

/**
 * Restrict to tasks that are assigned to users with the parameter value as a substring.
 * @member {String} taskAssigneeLike
 */
HistoricTaskInstanceQueryDto.prototype.taskAssigneeLike = undefined;

/**
 * Restrict to tasks that the given user owns.
 * @member {String} taskOwner
 */
HistoricTaskInstanceQueryDto.prototype.taskOwner = undefined;

/**
 * Restrict to tasks that are owned by users with the parameter value as a substring.
 * @member {String} taskOwnerLike
 */
HistoricTaskInstanceQueryDto.prototype.taskOwnerLike = undefined;

/**
 * Restrict to tasks that have the given priority.
 * @member {Number} taskPriority
 */
HistoricTaskInstanceQueryDto.prototype.taskPriority = undefined;

/**
 * If set to `true`, restricts the query to all tasks that are assigned.
 * @member {Boolean} assigned
 */
HistoricTaskInstanceQueryDto.prototype.assigned = undefined;

/**
 * If set to `true`, restricts the query to all tasks that are unassigned.
 * @member {Boolean} unassigned
 */
HistoricTaskInstanceQueryDto.prototype.unassigned = undefined;

/**
 * Only include finished tasks. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} finished
 */
HistoricTaskInstanceQueryDto.prototype.finished = undefined;

/**
 * Only include unfinished tasks. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} unfinished
 */
HistoricTaskInstanceQueryDto.prototype.unfinished = undefined;

/**
 * Only include tasks of finished processes. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} processFinished
 */
HistoricTaskInstanceQueryDto.prototype.processFinished = undefined;

/**
 * Only include tasks of unfinished processes. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} processUnfinished
 */
HistoricTaskInstanceQueryDto.prototype.processUnfinished = undefined;

/**
 * Restrict to tasks that are due on the given date. By [default](https://docs.camunda.org/manual/develop/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.000+0200`.
 * @member {Date} taskDueDate
 */
HistoricTaskInstanceQueryDto.prototype.taskDueDate = undefined;

/**
 * Restrict to tasks that are due before the given date. By [default](https://docs.camunda.org/manual/develop/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.000+0200`.
 * @member {Date} taskDueDateBefore
 */
HistoricTaskInstanceQueryDto.prototype.taskDueDateBefore = undefined;

/**
 * Restrict to tasks that are due after the given date. By [default](https://docs.camunda.org/manual/develop/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.000+0200`.
 * @member {Date} taskDueDateAfter
 */
HistoricTaskInstanceQueryDto.prototype.taskDueDateAfter = undefined;

/**
 * Only include tasks which have no due date. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} withoutTaskDueDate
 */
HistoricTaskInstanceQueryDto.prototype.withoutTaskDueDate = undefined;

/**
 * Restrict to tasks that have a followUp date on the given date. By [default](https://docs.camunda.org/manual/develop/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.000+0200`.
 * @member {Date} taskFollowUpDate
 */
HistoricTaskInstanceQueryDto.prototype.taskFollowUpDate = undefined;

/**
 * Restrict to tasks that have a followUp date before the given date. By [default](https://docs.camunda.org/manual/develop/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.000+0200`.
 * @member {Date} taskFollowUpDateBefore
 */
HistoricTaskInstanceQueryDto.prototype.taskFollowUpDateBefore = undefined;

/**
 * Restrict to tasks that have a followUp date after the given date. By [default](https://docs.camunda.org/manual/develop/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.000+0200`.
 * @member {Date} taskFollowUpDateAfter
 */
HistoricTaskInstanceQueryDto.prototype.taskFollowUpDateAfter = undefined;

/**
 * Restrict to tasks that were started before the given date. By [default](https://docs.camunda.org/manual/develop/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.000+0200`.
 * @member {Date} startedBefore
 */
HistoricTaskInstanceQueryDto.prototype.startedBefore = undefined;

/**
 * Restrict to tasks that were started after the given date. By [default](https://docs.camunda.org/manual/develop/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.000+0200`.
 * @member {Date} startedAfter
 */
HistoricTaskInstanceQueryDto.prototype.startedAfter = undefined;

/**
 * Restrict to tasks that were finished before the given date. By [default](https://docs.camunda.org/manual/develop/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.000+0200`.
 * @member {Date} finishedBefore
 */
HistoricTaskInstanceQueryDto.prototype.finishedBefore = undefined;

/**
 * Restrict to tasks that were finished after the given date. By [default](https://docs.camunda.org/manual/develop/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.000+0200`.
 * @member {Date} finishedAfter
 */
HistoricTaskInstanceQueryDto.prototype.finishedAfter = undefined;

/**
 * Filter by a  list of tenant ids. A task instance must have one of the given tenant ids.
 * @member {Array.<String>} tenantIdIn
 */
HistoricTaskInstanceQueryDto.prototype.tenantIdIn = undefined;

/**
 * Only include historic task instances that belong to no tenant. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} withoutTenantId
 */
HistoricTaskInstanceQueryDto.prototype.withoutTenantId = undefined;

/**
 * Only include tasks that have variables with certain values. Variable filtering expressions are comma-separated and are structured as follows:  A valid parameter value has the form `key_operator_value`. `key` is the variable name, `operator` is the comparison operator to be used and `value` the variable value. **Note:** Values are always treated as `String` objects on server side.   Valid operator values are: * `eq` - equal to; * `neq` - not equal to; * `gt` - greater than; * `gteq` - greater than or equal to; * `lt` - lower than; * `lteq` - lower than or equal to; * `like`.  `key` and `value` may not contain underscore or comma characters.
 * @member {Array.<module:model/VariableQueryParameterDto>} taskVariables
 */
HistoricTaskInstanceQueryDto.prototype.taskVariables = undefined;

/**
 * Only include tasks that belong to process instances that have variables with certain values. Variable filtering expressions are comma-separated and are structured as follows:  A valid parameter value has the form `key_operator_value`. `key` is the variable name, `operator` is the comparison operator to be used and `value` the variable value. **Note:** Values are always treated as `String` objects on server side.   Valid operator values are: * `eq` - equal to; * `neq` - not equal to; * `gt` - greater than; * `gteq` - greater than or equal to; * `lt` - lower than; * `lteq` - lower than or equal to; * `like`; * `notLike`.  `key` and `value` may not contain underscore or comma characters.
 * @member {Array.<module:model/VariableQueryParameterDto>} processVariables
 */
HistoricTaskInstanceQueryDto.prototype.processVariables = undefined;

/**
 * Match the variable name provided in `taskVariables` and `processVariables` case- insensitively. If set to `true` **variableName** and **variablename** are treated as equal.
 * @member {Boolean} variableNamesIgnoreCase
 */
HistoricTaskInstanceQueryDto.prototype.variableNamesIgnoreCase = undefined;

/**
 * Match the variable value provided in `taskVariables` and `processVariables` case- insensitively. If set to `true` **variableValue** and **variablevalue** are treated as equal.
 * @member {Boolean} variableValuesIgnoreCase
 */
HistoricTaskInstanceQueryDto.prototype.variableValuesIgnoreCase = undefined;

/**
 * Restrict to tasks with a historic identity link to the given user.
 * @member {String} taskInvolvedUser
 */
HistoricTaskInstanceQueryDto.prototype.taskInvolvedUser = undefined;

/**
 * Restrict to tasks with a historic identity link to the given group.
 * @member {String} taskInvolvedGroup
 */
HistoricTaskInstanceQueryDto.prototype.taskInvolvedGroup = undefined;

/**
 * Restrict to tasks with a historic identity link to the given candidate user.
 * @member {String} taskHadCandidateUser
 */
HistoricTaskInstanceQueryDto.prototype.taskHadCandidateUser = undefined;

/**
 * Restrict to tasks with a historic identity link to the given candidate group.
 * @member {String} taskHadCandidateGroup
 */
HistoricTaskInstanceQueryDto.prototype.taskHadCandidateGroup = undefined;

/**
 * Only include tasks which have a candidate group. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} withCandidateGroups
 */
HistoricTaskInstanceQueryDto.prototype.withCandidateGroups = undefined;

/**
 * Only include tasks which have no candidate group. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} withoutCandidateGroups
 */
HistoricTaskInstanceQueryDto.prototype.withoutCandidateGroups = undefined;

/**
 * A JSON array of nested historic task instance queries with OR semantics.  A task instance matches a nested query if it fulfills at least one of the query's predicates.  With multiple nested queries, a task instance must fulfill at least one predicate of each query ([Conjunctive Normal Form](https://en.wikipedia.org/wiki/Conjunctive_normal_form)).  All task instance query properties can be used except for: `sorting`, `withCandidateGroups`, ` withoutCandidateGroups`.  See the [User Guide](https://docs.camunda.org/manual/develop/user-guide/process-engine/process-engine-api/#or-queries) for more information about OR queries.
 * @member {Array.<module:model/HistoricTaskInstanceQueryDto>} orQueries
 */
HistoricTaskInstanceQueryDto.prototype.orQueries = undefined;

/**
 * An array of criteria to sort the result by. Each element of the array is                     an object that specifies one ordering. The position in the array                     identifies the rank of an ordering, i.e., whether it is primary, secondary,                     etc. Sorting has no effect for `count` endpoints
 * @member {Array.<module:model/HistoricTaskInstanceQueryDtoSorting>} sorting
 */
HistoricTaskInstanceQueryDto.prototype.sorting = undefined;

