/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The JobDefinitionDto model module.
 * @module model/JobDefinitionDto
 * @version 7.20.0
 */
export class JobDefinitionDto {
  /**
   * Constructs a new <code>JobDefinitionDto</code>.
   * @alias module:model/JobDefinitionDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>JobDefinitionDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JobDefinitionDto} obj Optional instance to populate.
   * @return {module:model/JobDefinitionDto} The populated <code>JobDefinitionDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new JobDefinitionDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('processDefinitionId'))
        obj.processDefinitionId = ApiClient.convertToType(data['processDefinitionId'], 'String');
      if (data.hasOwnProperty('processDefinitionKey'))
        obj.processDefinitionKey = ApiClient.convertToType(data['processDefinitionKey'], 'String');
      if (data.hasOwnProperty('activityId'))
        obj.activityId = ApiClient.convertToType(data['activityId'], 'String');
      if (data.hasOwnProperty('jobType'))
        obj.jobType = ApiClient.convertToType(data['jobType'], 'String');
      if (data.hasOwnProperty('jobConfiguration'))
        obj.jobConfiguration = ApiClient.convertToType(data['jobConfiguration'], 'String');
      if (data.hasOwnProperty('overridingJobPriority'))
        obj.overridingJobPriority = ApiClient.convertToType(data['overridingJobPriority'], 'Number');
      if (data.hasOwnProperty('suspended'))
        obj.suspended = ApiClient.convertToType(data['suspended'], 'Boolean');
      if (data.hasOwnProperty('tenantId'))
        obj.tenantId = ApiClient.convertToType(data['tenantId'], 'String');
      if (data.hasOwnProperty('deploymentId'))
        obj.deploymentId = ApiClient.convertToType(data['deploymentId'], 'String');
    }
    return obj;
  }
}

/**
 * The id of the job definition.
 * @member {String} id
 */
JobDefinitionDto.prototype.id = undefined;

/**
 * The id of the process definition this job definition is associated with.
 * @member {String} processDefinitionId
 */
JobDefinitionDto.prototype.processDefinitionId = undefined;

/**
 * The key of the process definition this job definition is associated with.
 * @member {String} processDefinitionKey
 */
JobDefinitionDto.prototype.processDefinitionKey = undefined;

/**
 * The id of the activity this job definition is associated with.
 * @member {String} activityId
 */
JobDefinitionDto.prototype.activityId = undefined;

/**
 * The type of the job which is running for this job definition. See the [User Guide](https://docs.camunda.org/manual/develop/user-guide/process-engine/the-job-executor/#job-creation) for more information about job types.
 * @member {String} jobType
 */
JobDefinitionDto.prototype.jobType = undefined;

/**
 * The configuration of a job definition provides details about the jobs which will be created. For example: for timer jobs it is the timer configuration.
 * @member {String} jobConfiguration
 */
JobDefinitionDto.prototype.jobConfiguration = undefined;

/**
 * The execution priority defined for jobs that are created based on this definition. May be `null` when the priority has not been overridden on the job definition level.
 * @member {Number} overridingJobPriority
 */
JobDefinitionDto.prototype.overridingJobPriority = undefined;

/**
 * Indicates whether this job definition is suspended or not.
 * @member {Boolean} suspended
 */
JobDefinitionDto.prototype.suspended = undefined;

/**
 * The id of the tenant this job definition is associated with.
 * @member {String} tenantId
 */
JobDefinitionDto.prototype.tenantId = undefined;

/**
 * The id of the deployment this job definition is related to. In a deployment-aware setup, this leads to all jobs of the same definition being executed on the same node.
 * @member {String} deploymentId
 */
JobDefinitionDto.prototype.deploymentId = undefined;

