/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {JobDefinitionQueryDtoSorting} from './JobDefinitionQueryDtoSorting';

/**
 * The JobDefinitionQueryDto model module.
 * @module model/JobDefinitionQueryDto
 * @version 7.20.0
 */
export class JobDefinitionQueryDto {
  /**
   * Constructs a new <code>JobDefinitionQueryDto</code>.
   * A Job definition query which defines a list of Job definitions
   * @alias module:model/JobDefinitionQueryDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>JobDefinitionQueryDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JobDefinitionQueryDto} obj Optional instance to populate.
   * @return {module:model/JobDefinitionQueryDto} The populated <code>JobDefinitionQueryDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new JobDefinitionQueryDto();
      if (data.hasOwnProperty('jobDefinitionId'))
        obj.jobDefinitionId = ApiClient.convertToType(data['jobDefinitionId'], 'String');
      if (data.hasOwnProperty('activityIdIn'))
        obj.activityIdIn = ApiClient.convertToType(data['activityIdIn'], ['String']);
      if (data.hasOwnProperty('processDefinitionId'))
        obj.processDefinitionId = ApiClient.convertToType(data['processDefinitionId'], 'String');
      if (data.hasOwnProperty('processDefinitionKey'))
        obj.processDefinitionKey = ApiClient.convertToType(data['processDefinitionKey'], 'String');
      if (data.hasOwnProperty('jobType'))
        obj.jobType = ApiClient.convertToType(data['jobType'], 'String');
      if (data.hasOwnProperty('jobConfiguration'))
        obj.jobConfiguration = ApiClient.convertToType(data['jobConfiguration'], 'String');
      if (data.hasOwnProperty('active'))
        obj.active = ApiClient.convertToType(data['active'], 'Boolean');
      if (data.hasOwnProperty('suspended'))
        obj.suspended = ApiClient.convertToType(data['suspended'], 'Boolean');
      if (data.hasOwnProperty('withOverridingJobPriority'))
        obj.withOverridingJobPriority = ApiClient.convertToType(data['withOverridingJobPriority'], 'Boolean');
      if (data.hasOwnProperty('tenantIdIn'))
        obj.tenantIdIn = ApiClient.convertToType(data['tenantIdIn'], ['String']);
      if (data.hasOwnProperty('withoutTenantId'))
        obj.withoutTenantId = ApiClient.convertToType(data['withoutTenantId'], 'Boolean');
      if (data.hasOwnProperty('includeJobDefinitionsWithoutTenantId'))
        obj.includeJobDefinitionsWithoutTenantId = ApiClient.convertToType(data['includeJobDefinitionsWithoutTenantId'], 'Boolean');
      if (data.hasOwnProperty('sorting'))
        obj.sorting = ApiClient.convertToType(data['sorting'], [JobDefinitionQueryDtoSorting]);
    }
    return obj;
  }
}

/**
 * Filter by job definition id.
 * @member {String} jobDefinitionId
 */
JobDefinitionQueryDto.prototype.jobDefinitionId = undefined;

/**
 * Only include job definitions which belong to one of the passed activity ids.
 * @member {Array.<String>} activityIdIn
 */
JobDefinitionQueryDto.prototype.activityIdIn = undefined;

/**
 * Only include job definitions which exist for the given process definition id.
 * @member {String} processDefinitionId
 */
JobDefinitionQueryDto.prototype.processDefinitionId = undefined;

/**
 * Only include job definitions which exist for the given process definition key.
 * @member {String} processDefinitionKey
 */
JobDefinitionQueryDto.prototype.processDefinitionKey = undefined;

/**
 * Only include job definitions which exist for the given job type. See the [User Guide](https://docs.camunda.org/manual/develop/user-guide/process-engine/the-job-executor/#job-creation) for more information about job types.
 * @member {String} jobType
 */
JobDefinitionQueryDto.prototype.jobType = undefined;

/**
 * Only include job definitions which exist for the given job configuration. For example: for timer jobs it is the timer configuration.
 * @member {String} jobConfiguration
 */
JobDefinitionQueryDto.prototype.jobConfiguration = undefined;

/**
 * Only include active job definitions. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} active
 */
JobDefinitionQueryDto.prototype.active = undefined;

/**
 * Only include suspended job definitions. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} suspended
 */
JobDefinitionQueryDto.prototype.suspended = undefined;

/**
 * Only include job definitions that have an overriding job priority defined. The only effective value is `true`. If set to `false`, this filter is not applied.
 * @member {Boolean} withOverridingJobPriority
 */
JobDefinitionQueryDto.prototype.withOverridingJobPriority = undefined;

/**
 * Only include job definitions which belong to one of the passed tenant ids.
 * @member {Array.<String>} tenantIdIn
 */
JobDefinitionQueryDto.prototype.tenantIdIn = undefined;

/**
 * Only include job definitions which belong to no tenant. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} withoutTenantId
 */
JobDefinitionQueryDto.prototype.withoutTenantId = undefined;

/**
 * Include job definitions which belong to no tenant. Can be used in combination with `tenantIdIn`. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} includeJobDefinitionsWithoutTenantId
 */
JobDefinitionQueryDto.prototype.includeJobDefinitionsWithoutTenantId = undefined;

/**
 * An array of criteria to sort the result by. Each element of the array is                        an object that specifies one ordering. The position in the array                        identifies the rank of an ordering, i.e., whether it is primary, secondary,                        etc. Sorting has no effect for `count` endpoints.
 * @member {Array.<module:model/JobDefinitionQueryDtoSorting>} sorting
 */
JobDefinitionQueryDto.prototype.sorting = undefined;

