/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The JobQueryDtoSorting model module.
 * @module model/JobQueryDtoSorting
 * @version 7.20.0
 */
export class JobQueryDtoSorting {
  /**
   * Constructs a new <code>JobQueryDtoSorting</code>.
   * @alias module:model/JobQueryDtoSorting
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>JobQueryDtoSorting</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JobQueryDtoSorting} obj Optional instance to populate.
   * @return {module:model/JobQueryDtoSorting} The populated <code>JobQueryDtoSorting</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new JobQueryDtoSorting();
      if (data.hasOwnProperty('sortBy'))
        obj.sortBy = ApiClient.convertToType(data['sortBy'], 'String');
      if (data.hasOwnProperty('sortOrder'))
        obj.sortOrder = ApiClient.convertToType(data['sortOrder'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>sortBy</code> property.
 * @enum {String}
 * @readonly
 */
JobQueryDtoSorting.SortByEnum = {
  /**
   * value: "jobId"
   * @const
   */
  jobId: "jobId",

  /**
   * value: "executionId"
   * @const
   */
  executionId: "executionId",

  /**
   * value: "processInstanceId"
   * @const
   */
  processInstanceId: "processInstanceId",

  /**
   * value: "processDefinitionId"
   * @const
   */
  processDefinitionId: "processDefinitionId",

  /**
   * value: "processDefinitionKey"
   * @const
   */
  processDefinitionKey: "processDefinitionKey",

  /**
   * value: "jobPriority"
   * @const
   */
  jobPriority: "jobPriority",

  /**
   * value: "jobRetries"
   * @const
   */
  jobRetries: "jobRetries",

  /**
   * value: "jobDueDate"
   * @const
   */
  jobDueDate: "jobDueDate",

  /**
   * value: "tenantId"
   * @const
   */
  tenantId: "tenantId"
};
/**
 * Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter.
 * @member {module:model/JobQueryDtoSorting.SortByEnum} sortBy
 */
JobQueryDtoSorting.prototype.sortBy = undefined;

/**
 * Allowed values for the <code>sortOrder</code> property.
 * @enum {String}
 * @readonly
 */
JobQueryDtoSorting.SortOrderEnum = {
  /**
   * value: "asc"
   * @const
   */
  asc: "asc",

  /**
   * value: "desc"
   * @const
   */
  desc: "desc"
};
/**
 * Sort the results in a given order. Values may be `asc` for ascending order or `desc` for descending order. Must be used in conjunction with the sortBy parameter.
 * @member {module:model/JobQueryDtoSorting.SortOrderEnum} sortOrder
 */
JobQueryDtoSorting.prototype.sortOrder = undefined;

