/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MigrationInstructionDto model module.
 * @module model/MigrationInstructionDto
 * @version 7.20.0
 */
export class MigrationInstructionDto {
  /**
   * Constructs a new <code>MigrationInstructionDto</code>.
   * @alias module:model/MigrationInstructionDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MigrationInstructionDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MigrationInstructionDto} obj Optional instance to populate.
   * @return {module:model/MigrationInstructionDto} The populated <code>MigrationInstructionDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MigrationInstructionDto();
      if (data.hasOwnProperty('sourceActivityIds'))
        obj.sourceActivityIds = ApiClient.convertToType(data['sourceActivityIds'], ['String']);
      if (data.hasOwnProperty('targetActivityIds'))
        obj.targetActivityIds = ApiClient.convertToType(data['targetActivityIds'], ['String']);
      if (data.hasOwnProperty('updateEventTrigger'))
        obj.updateEventTrigger = ApiClient.convertToType(data['updateEventTrigger'], 'Boolean');
    }
    return obj;
  }
}

/**
 * The activity ids from the source process definition being mapped.
 * @member {Array.<String>} sourceActivityIds
 */
MigrationInstructionDto.prototype.sourceActivityIds = undefined;

/**
 * The activity ids from the target process definition being mapped.
 * @member {Array.<String>} targetActivityIds
 */
MigrationInstructionDto.prototype.targetActivityIds = undefined;

/**
 * Configuration flag whether event triggers defined are going to be updated during migration.
 * @member {Boolean} updateEventTrigger
 */
MigrationInstructionDto.prototype.updateEventTrigger = undefined;

