/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AtomLink} from './AtomLink';
import {LinkableDto} from './LinkableDto';

/**
 * The ProcessInstanceDto model module.
 * @module model/ProcessInstanceDto
 * @version 7.20.0
 */
export class ProcessInstanceDto {
  /**
   * Constructs a new <code>ProcessInstanceDto</code>.
   * @alias module:model/ProcessInstanceDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProcessInstanceDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProcessInstanceDto} obj Optional instance to populate.
   * @return {module:model/ProcessInstanceDto} The populated <code>ProcessInstanceDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProcessInstanceDto();
      if (data.hasOwnProperty('links'))
        obj.links = ApiClient.convertToType(data['links'], [AtomLink]);
    }
    return obj;
  }
}

/**
 * The links associated to this resource, with `method`, `href` and `rel`.
 * @member {Array.<module:model/AtomLink>} links
 */
ProcessInstanceDto.prototype.links = undefined;

