/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {UserCredentialsDto} from './UserCredentialsDto';
import {UserProfileDto} from './UserProfileDto';

/**
 * The UserDto model module.
 * @module model/UserDto
 * @version 7.20.0
 */
export class UserDto {
  /**
   * Constructs a new <code>UserDto</code>.
   * @alias module:model/UserDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserDto} obj Optional instance to populate.
   * @return {module:model/UserDto} The populated <code>UserDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserDto();
      if (data.hasOwnProperty('profile'))
        obj.profile = UserProfileDto.constructFromObject(data['profile']);
      if (data.hasOwnProperty('credentials'))
        obj.credentials = UserCredentialsDto.constructFromObject(data['credentials']);
    }
    return obj;
  }
}

/**
 * @member {module:model/UserProfileDto} profile
 */
UserDto.prototype.profile = undefined;

/**
 * @member {module:model/UserCredentialsDto} credentials
 */
UserDto.prototype.credentials = undefined;

