/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CamundaRestApi);
  }
}(this, function(expect, CamundaRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DeleteHistoricProcessInstancesDto', function() {
      beforeEach(function() {
        instance = new CamundaRestApi.DeleteHistoricProcessInstancesDto();
      });

      it('should create an instance of DeleteHistoricProcessInstancesDto', function() {
        // TODO: update the code to test DeleteHistoricProcessInstancesDto
        expect(instance).to.be.a(CamundaRestApi.DeleteHistoricProcessInstancesDto);
      });

      it('should have the property historicProcessInstanceIds (base name: "historicProcessInstanceIds")', function() {
        // TODO: update the code to test the property historicProcessInstanceIds
        expect(instance).to.have.property('historicProcessInstanceIds');
        // expect(instance.historicProcessInstanceIds).to.be(expectedValueLiteral);
      });

      it('should have the property historicProcessInstanceQuery (base name: "historicProcessInstanceQuery")', function() {
        // TODO: update the code to test the property historicProcessInstanceQuery
        expect(instance).to.have.property('historicProcessInstanceQuery');
        // expect(instance.historicProcessInstanceQuery).to.be(expectedValueLiteral);
      });

      it('should have the property deleteReason (base name: "deleteReason")', function() {
        // TODO: update the code to test the property deleteReason
        expect(instance).to.have.property('deleteReason');
        // expect(instance.deleteReason).to.be(expectedValueLiteral);
      });

      it('should have the property failIfNotExists (base name: "failIfNotExists")', function() {
        // TODO: update the code to test the property failIfNotExists
        expect(instance).to.have.property('failIfNotExists');
        // expect(instance.failIfNotExists).to.be(expectedValueLiteral);
      });

    });
  });

}));
