/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CamundaRestApi);
  }
}(this, function(expect, CamundaRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('UserCredentialsDto', function() {
      beforeEach(function() {
        instance = new CamundaRestApi.UserCredentialsDto();
      });

      it('should create an instance of UserCredentialsDto', function() {
        // TODO: update the code to test UserCredentialsDto
        expect(instance).to.be.a(CamundaRestApi.UserCredentialsDto);
      });

      it('should have the property password (base name: "password")', function() {
        // TODO: update the code to test the property password
        expect(instance).to.have.property('password');
        // expect(instance.password).to.be(expectedValueLiteral);
      });

      it('should have the property authenticatedUserPassword (base name: "authenticatedUserPassword")', function() {
        // TODO: update the code to test the property authenticatedUserPassword
        expect(instance).to.have.property('authenticatedUserPassword');
        // expect(instance.authenticatedUserPassword).to.be(expectedValueLiteral);
      });

    });
  });

}));
