/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CamundaRestApi);
  }
}(this, function(expect, CamundaRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('VariableInstanceQueryDto', function() {
      beforeEach(function() {
        instance = new CamundaRestApi.VariableInstanceQueryDto();
      });

      it('should create an instance of VariableInstanceQueryDto', function() {
        // TODO: update the code to test VariableInstanceQueryDto
        expect(instance).to.be.a(CamundaRestApi.VariableInstanceQueryDto);
      });

      it('should have the property variableName (base name: "variableName")', function() {
        // TODO: update the code to test the property variableName
        expect(instance).to.have.property('variableName');
        // expect(instance.variableName).to.be(expectedValueLiteral);
      });

      it('should have the property variableNameLike (base name: "variableNameLike")', function() {
        // TODO: update the code to test the property variableNameLike
        expect(instance).to.have.property('variableNameLike');
        // expect(instance.variableNameLike).to.be(expectedValueLiteral);
      });

      it('should have the property processInstanceIdIn (base name: "processInstanceIdIn")', function() {
        // TODO: update the code to test the property processInstanceIdIn
        expect(instance).to.have.property('processInstanceIdIn');
        // expect(instance.processInstanceIdIn).to.be(expectedValueLiteral);
      });

      it('should have the property executionIdIn (base name: "executionIdIn")', function() {
        // TODO: update the code to test the property executionIdIn
        expect(instance).to.have.property('executionIdIn');
        // expect(instance.executionIdIn).to.be(expectedValueLiteral);
      });

      it('should have the property caseInstanceIdIn (base name: "caseInstanceIdIn")', function() {
        // TODO: update the code to test the property caseInstanceIdIn
        expect(instance).to.have.property('caseInstanceIdIn');
        // expect(instance.caseInstanceIdIn).to.be(expectedValueLiteral);
      });

      it('should have the property caseExecutionIdIn (base name: "caseExecutionIdIn")', function() {
        // TODO: update the code to test the property caseExecutionIdIn
        expect(instance).to.have.property('caseExecutionIdIn');
        // expect(instance.caseExecutionIdIn).to.be(expectedValueLiteral);
      });

      it('should have the property taskIdIn (base name: "taskIdIn")', function() {
        // TODO: update the code to test the property taskIdIn
        expect(instance).to.have.property('taskIdIn');
        // expect(instance.taskIdIn).to.be(expectedValueLiteral);
      });

      it('should have the property batchIdIn (base name: "batchIdIn")', function() {
        // TODO: update the code to test the property batchIdIn
        expect(instance).to.have.property('batchIdIn');
        // expect(instance.batchIdIn).to.be(expectedValueLiteral);
      });

      it('should have the property activityInstanceIdIn (base name: "activityInstanceIdIn")', function() {
        // TODO: update the code to test the property activityInstanceIdIn
        expect(instance).to.have.property('activityInstanceIdIn');
        // expect(instance.activityInstanceIdIn).to.be(expectedValueLiteral);
      });

      it('should have the property tenantIdIn (base name: "tenantIdIn")', function() {
        // TODO: update the code to test the property tenantIdIn
        expect(instance).to.have.property('tenantIdIn');
        // expect(instance.tenantIdIn).to.be(expectedValueLiteral);
      });

      it('should have the property variableValues (base name: "variableValues")', function() {
        // TODO: update the code to test the property variableValues
        expect(instance).to.have.property('variableValues');
        // expect(instance.variableValues).to.be(expectedValueLiteral);
      });

      it('should have the property variableNamesIgnoreCase (base name: "variableNamesIgnoreCase")', function() {
        // TODO: update the code to test the property variableNamesIgnoreCase
        expect(instance).to.have.property('variableNamesIgnoreCase');
        // expect(instance.variableNamesIgnoreCase).to.be(expectedValueLiteral);
      });

      it('should have the property variableValuesIgnoreCase (base name: "variableValuesIgnoreCase")', function() {
        // TODO: update the code to test the property variableValuesIgnoreCase
        expect(instance).to.have.property('variableValuesIgnoreCase');
        // expect(instance.variableValuesIgnoreCase).to.be(expectedValueLiteral);
      });

      it('should have the property variableScopeIdIn (base name: "variableScopeIdIn")', function() {
        // TODO: update the code to test the property variableScopeIdIn
        expect(instance).to.have.property('variableScopeIdIn');
        // expect(instance.variableScopeIdIn).to.be(expectedValueLiteral);
      });

      it('should have the property sorting (base name: "sorting")', function() {
        // TODO: update the code to test the property sorting
        expect(instance).to.have.property('sorting');
        // expect(instance.sorting).to.be(expectedValueLiteral);
      });

    });
  });

}));
