/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CamundaRestApi);
  }
}(this, function(expect, CamundaRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CamundaRestApi.IdentityApi();
  });

  describe('(package)', function() {
    describe('IdentityApi', function() {
      describe('checkPassword', function() {
        it('should call checkPassword successfully', function(done) {
          // TODO: uncomment, update parameter values for checkPassword call and complete the assertions
          /*
          var opts = {};

          instance.checkPassword(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CamundaRestApi.CheckPasswordPolicyResultDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getGroupInfo', function() {
        it('should call getGroupInfo successfully', function(done) {
          // TODO: uncomment, update parameter values for getGroupInfo call and complete the assertions
          /*

          instance.getGroupInfo(userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CamundaRestApi.IdentityServiceGroupInfoDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getPasswordPolicy', function() {
        it('should call getPasswordPolicy successfully', function(done) {
          // TODO: uncomment getPasswordPolicy call and complete the assertions
          /*

          instance.getPasswordPolicy(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CamundaRestApi.PasswordPolicyDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('verifyUser', function() {
        it('should call verifyUser successfully', function(done) {
          // TODO: uncomment, update parameter values for verifyUser call and complete the assertions
          /*
          var opts = {};

          instance.verifyUser(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CamundaRestApi.AuthenticationResult);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
