/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CamundaRestApi);
  }
}(this, function(expect, CamundaRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CamundaRestApi.IncidentApi();
  });

  describe('(package)', function() {
    describe('IncidentApi', function() {
      describe('clearIncidentAnnotation', function() {
        it('should call clearIncidentAnnotation successfully', function(done) {
          // TODO: uncomment, update parameter values for clearIncidentAnnotation call
          /*

          instance.clearIncidentAnnotation(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getIncident', function() {
        it('should call getIncident successfully', function(done) {
          // TODO: uncomment, update parameter values for getIncident call and complete the assertions
          /*

          instance.getIncident(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CamundaRestApi.IncidentDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getIncidents', function() {
        it('should call getIncidents successfully', function(done) {
          // TODO: uncomment, update parameter values for getIncidents call and complete the assertions
          /*
          var opts = {};

          instance.getIncidents(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(CamundaRestApi.IncidentDto);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getIncidentsCount', function() {
        it('should call getIncidentsCount successfully', function(done) {
          // TODO: uncomment, update parameter values for getIncidentsCount call and complete the assertions
          /*
          var opts = {};

          instance.getIncidentsCount(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CamundaRestApi.CountResultDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('resolveIncident', function() {
        it('should call resolveIncident successfully', function(done) {
          // TODO: uncomment, update parameter values for resolveIncident call
          /*

          instance.resolveIncident(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setIncidentAnnotation', function() {
        it('should call setIncidentAnnotation successfully', function(done) {
          // TODO: uncomment, update parameter values for setIncidentAnnotation call
          /*
          var opts = {};

          instance.setIncidentAnnotation(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
