/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CamundaRestApi);
  }
}(this, function(expect, CamundaRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CamundaRestApi.MigrationApi();
  });

  describe('(package)', function() {
    describe('MigrationApi', function() {
      describe('executeMigrationPlan', function() {
        it('should call executeMigrationPlan successfully', function(done) {
          // TODO: uncomment, update parameter values for executeMigrationPlan call
          /*
          var opts = {};

          instance.executeMigrationPlan(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('executeMigrationPlanAsync', function() {
        it('should call executeMigrationPlanAsync successfully', function(done) {
          // TODO: uncomment, update parameter values for executeMigrationPlanAsync call and complete the assertions
          /*
          var opts = {};

          instance.executeMigrationPlanAsync(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CamundaRestApi.BatchDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('generateMigrationPlan', function() {
        it('should call generateMigrationPlan successfully', function(done) {
          // TODO: uncomment, update parameter values for generateMigrationPlan call and complete the assertions
          /*
          var opts = {};

          instance.generateMigrationPlan(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CamundaRestApi.MigrationPlanDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('validateMigrationPlan', function() {
        it('should call validateMigrationPlan successfully', function(done) {
          // TODO: uncomment, update parameter values for validateMigrationPlan call and complete the assertions
          /*
          var opts = {};

          instance.validateMigrationPlan(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CamundaRestApi.MigrationPlanReportDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
