/*
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.20.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CamundaRestApi);
  }
}(this, function(expect, CamundaRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CamundaRestApi.TaskLocalVariableApi();
  });

  describe('(package)', function() {
    describe('TaskLocalVariableApi', function() {
      describe('deleteTaskLocalVariable', function() {
        it('should call deleteTaskLocalVariable successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteTaskLocalVariable call
          /*

          instance.deleteTaskLocalVariable(id, varName, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTaskLocalVariable', function() {
        it('should call getTaskLocalVariable successfully', function(done) {
          // TODO: uncomment, update parameter values for getTaskLocalVariable call and complete the assertions
          /*
          var opts = {};

          instance.getTaskLocalVariable(id, varName, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CamundaRestApi.VariableValueDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTaskLocalVariableBinary', function() {
        it('should call getTaskLocalVariableBinary successfully', function(done) {
          // TODO: uncomment, update parameter values for getTaskLocalVariableBinary call and complete the assertions
          /*

          instance.getTaskLocalVariableBinary(id, varName, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Blob);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTaskLocalVariables', function() {
        it('should call getTaskLocalVariables successfully', function(done) {
          // TODO: uncomment, update parameter values for getTaskLocalVariables call and complete the assertions
          /*
          var opts = {};

          instance.getTaskLocalVariables(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Object);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(CamundaRestApi.VariableValueDto);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('modifyTaskLocalVariables', function() {
        it('should call modifyTaskLocalVariables successfully', function(done) {
          // TODO: uncomment, update parameter values for modifyTaskLocalVariables call
          /*
          var opts = {};

          instance.modifyTaskLocalVariables(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('putTaskLocalVariable', function() {
        it('should call putTaskLocalVariable successfully', function(done) {
          // TODO: uncomment, update parameter values for putTaskLocalVariable call
          /*
          var opts = {};

          instance.putTaskLocalVariable(id, varName, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setBinaryTaskLocalVariable', function() {
        it('should call setBinaryTaskLocalVariable successfully', function(done) {
          // TODO: uncomment, update parameter values for setBinaryTaskLocalVariable call
          /*
          var opts = {};

          instance.setBinaryTaskLocalVariable(id, varName, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
